### ISSUE TITLE
False negative on Conventional PR

### ISSUE THREAD

**Issue by Namchee** [Namchee/halp#27]
I'm using Conventional PR to prevent commits with bad messages to be merged to the main branch. I'm using the default conventional commit pattern

`^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\([\w\-\.]+\))?(!)?: ([\w ])+([\s\S]*)`

However, it seems commit messages like test commit is still considered to be valid. It seems like the conventional PR doesn't filter commit messages correctly.

**Comment by Namchee** [comment]
Thanks for filing an issue.

The pattern seems fine, can you post the action workflow file here?

**Comment by Namchee** [comment]
Sure, here you go

```yaml
name: Check PR semantics

on:
  pull_request_target:

jobs:
  cpr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR semantics
        uses: Namchee/conventional-pr@latest
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          title_pattern: ^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\([\w\-\.]+\))?(!)?: ([\w ])+([\s\S]*)
```
